In [1]:
import numpy as np

In [6]:
# array define in numpy
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# list -> python
l = [1,2,3,4,5,6,7,8,9]
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
# 2D array through list 
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
# 2D matrix through numpy or matrix in numpy
arr2 = np.array(l)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Generation Function** 

In [13]:
arr = np.arange(1,11) # make an array of elements from 1 to 10 (1, n+1) 
arr
arr2 = np.arange(1,11,2) # 2 ke gap par elements honge 
arr2

array([1, 3, 5, 7, 9])

In [19]:
arr = np.zeros(5) # array with all elements as "0"
arr
arr2 = np.zeros((4,4)) # n x n matrix with all elements as "0"
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
arr = np.ones(5) # array with all elements as "1"
arr
arr2 = np.ones((6,6)) # n x n matrix with all elements as "1"
arr2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
# for linear spacing between elements
arr = np.linspace(0,10,2) # (start_point, end_point, number_of_elements) -> yeh end point tak numbers dega means end_point is included
arr
arr2 = np.linspace(0,10,100)
arr2

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ,
        1.11111111,  1.22222222,  1.33333333,  1.44444444,  1.55555556,
        1.66666667,  1.77777778,  1.88888889,  2.        ,  2.11111111,
        2.22222222,  2.33333333,  2.44444444,  2.55555556,  2.66666667,
        2.77777778,  2.88888889,  3.        ,  3.11111111,  3.22222222,
        3.33333333,  3.44444444,  3.55555556,  3.66666667,  3.77777778,
        3.88888889,  4.        ,  4.11111111,  4.22222222,  4.33333333,
        4.44444444,  4.55555556,  4.66666667,  4.77777778,  4.88888889,
        5.        ,  5.11111111,  5.22222222,  5.33333333,  5.44444444,
        5.55555556,  5.66666667,  5.77777778,  5.88888889,  6.        ,
        6.11111111,  6.22222222,  6.33333333,  6.44444444,  6.55555556,
        6.66666667,  6.77777778,  6.88888889,  7.        ,  7.11111111,
        7.22222222,  7.33333333,  7.44444444,  7.55555556,  7.66

**Random Generation Function**

In [29]:
np.random.rand(10) # normalization : 0 to 1

array([0.00743125, 0.56265636, 0.53285772, 0.67362871, 0.20952993,
       0.99967877, 0.31954831, 0.70020552, 0.45054447, 0.83592153])

In [31]:
np.random.randn(10) # standardization : -3 to 3

array([ 3.03086140e-01,  7.48902054e-05, -6.89759439e-01,  7.15891789e-01,
        5.70084122e-01,  5.11017988e-01,  1.02057552e-01, -9.15593067e-01,
        3.37497785e-01,  7.77840797e-01])

In [36]:
np.random.randint(10,20,10) # any integer -> (start_point, end_point, number_of_elements)

array([19, 10, 13, 12, 14, 15, 18, 10, 12, 18], dtype=int32)

**Array attributes**

In [37]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

**Array Methods**

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [44]:
arr.sum() # sum of all elements

np.int64(45)

In [45]:
np.sum(arr, axis = 1) # sum of each row {axis = 1 -> is used for rows}

array([ 6, 15, 24])

In [48]:
np.sum(arr, axis = 0) # sum of column row {axis = 0 -> is used for columns}

array([12, 15, 18])

In [49]:
arr.mean()

np.float64(5.0)

In [51]:
arr.std() # standard deviation

np.float64(2.581988897471611)

In [52]:
arr.argmax() # index of the maximum value

np.int64(8)

In [53]:
arr.argmin() # index of the minimum value

np.int64(0)

**Reshaping and resizing**

In [55]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [59]:
arr = arr.reshape(6,5)
arr 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])