In [1]:
import numpy as np

**NUMPY INDEXING AND SLICING OF VECTORS**

In [5]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr_slice = arr[2:5] # (start_idx, end_idx) -> (i0,j0)
arr_slice
# i0, i1, i2, i3, ......, j3, j2, j1 -> means : include first_index and (last_index - 1)

array([13, 14, 15])

In [7]:
arr_slice = arr[3::2] # print elements from the start_idx to the last element with k gaps
arr_slice
# (start_idx :: k)

array([14, 16, 18, 20])

In [10]:
arr_slice = arr[:5] # or (0:5)
arr_slice

array([11, 12, 13, 14, 15])

In [11]:
arr_slice = arr[3:] # or (start_idx : last_element)
arr_slice

array([14, 15, 16, 17, 18, 19, 20])

**NUMPY INDEXING AND SLICING OF MATRIX**

In [12]:
arr = np.arange(1,31).reshape((6,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr[0] # print index-0 row

array([1, 2, 3, 4, 5])

In [19]:
arr[4] # print index-4 row 

array([21, 22, 23, 24, 25])

In [23]:
arr[:,0] # print index-0 column

array([ 1,  6, 11, 16, 21, 26])

In [24]:
arr[:,3] # pritn index-3 column

array([ 4,  9, 14, 19, 24, 29])

In [26]:
arr[3:, 3:] # portion of matrix using slicing

array([[19, 20],
       [24, 25],
       [29, 30]])

**BOOLEAN INDEXING**

In [27]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# i want to print only evens number