In [1]:
import numpy as np

**Array Operations**

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [19]:
l = [10, 20, 30, 40, 50] # list
# now i want to add 10 in each element 
# l + 10 is not possible because l is the list so convert into array
arr = np.array(l)
arr + 10

array([20, 30, 40, 50, 60])

In [20]:
arr = np.arange(42, 91, 2).reshape((5,5))
arr

array([[42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80],
       [82, 84, 86, 88, 90]])

In [21]:
arr + 10 

array([[ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

**Deep and Shallow copy**

In [23]:
original_array = np.array([1, 2, 3, 4, 5])
shallow_copy = original_array.view()
# Modify the shallow copy
shallow_copy[0] = 99
print(f"Original array: {original_array}") # Output: [99, 2, 3, 4, 5]
print(f"Shallow copy: {shallow_copy}")     # Output: [99, 2, 3, 4, 5]

Original array: [99  2  3  4  5]
Shallow copy: [99  2  3  4  5]


In [24]:
original_array = np.array([1, 2, 3, 4, 5])
deep_copy = original_array.copy()
# Modify the deep copy
deep_copy[0] = 99
print(f"Original array: {original_array}") # Output: [1, 2, 3, 4, 5]
print(f"Deep copy: {deep_copy}")     # Output: [99, 2, 3, 4, 5]

Original array: [1 2 3 4 5]
Deep copy: [99  2  3  4  5]


**Matrix operations**

In [26]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [27]:
A

array([[1, 2],
       [3, 4]])

In [28]:
B

array([[5, 6],
       [7, 8]])

In [30]:
np.dot(A,B) # for multiplication of two matrix A*B is not possible

array([[19, 22],
       [43, 50]])

In [32]:
A.T # transpose of matrix

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

In [33]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [34]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Splitting Array**